### ISSUE TITLE
TerraformのCI/CD 

### ISSUE THREAD

**Issue by jinugasachio** [jinugasachio/advanced-ecs-on-fargate#1]
## ツールの選択肢
- CircleCI
- GitHub Actions
- Terraform cloud
- AWS CodeBuild

## CI/CD でやること
- [x] terraform init
- [x] terraform fmt
- [ ] tflint
- [x] terraform/provider の update  → https://github.com/jinugasachio/advanced-ecs-on-fargate/issues/38 で対応する
- [x] terraform validate
- [x] terraform plan
  - [x] 結果を PRにコメント（tfnotify）
- [x] terraform apply（main/masterブランチのみ） 
  - [x] 結果を PRにコメント（tfnotify）

**Comment by yukio-ugajin** [comment]
circleciからcodebuildに移した話、その理由も書かれている
- [Terraform の CI/CD を CodeBuild に移行した話](https://blog.studysapuri.jp/entry/2020/12/03/080000)

**Comment by yukio-ugajin** [comment]
developにpushされたらstagingへapply、mainならproductionへapply
と考えていたが、環境をディレクトリで分ける構成の場合よくわからないことになる。

ので、developとかは特に用意せず、単に「mainにpushされたらapply」で良さそう。stagingとproduction両方にapplyされる場合もある。

**Comment by yukio-ugajin** [comment]
## 差分があるディレクトリのみでplanを実行する方法

- [メルカリ](https://engineering.mercari.com/blog/entry/2018-04-09-110000)
```
- set -e
basedir="$1"
if is_there_no_change "$basedir"; then
echo "[INFO] No changes in $basedir"
exit 0
fi
if is_branch_behind_master; then
echo "[INFO] Skipped because $current_branch is behind of master"
exit 0
fi
echo "[INFO] Running 'terraform plan' for changed dirs"
for dir in $(changed_dirs "$basedir")
do
./script/terraform-plan "$dir" | tfnotify plan --message "$dir"
done
```

- [mixi]()
```
#!/bin/sh -xe
export EXCLUDE_DIRS='^\.|scripts|bin'
DIRS=$(git --no-pager diff origin/master..HEAD --name-only | xargs -I {} dirname {} | egrep -v "$EXCLUDE_DIRS" | uniq)
if [ -z "$DIRS" ]; then
  echo "No directories for plan."
  exit 0
fi
for dir in $DIRS
do
  (cd $dir && terraform init -input=false -no-color)
  (cd $dir && terraform plan -input=false -no-color | ../bin/tfnotify --config ../.tfnotify.yml plan --message "$dir")
done
```

**Comment by yukio-ugajin** [comment]
流れとしては
1. 差分があるファイルのディレクトリを全て取得
2. 上記の各ディレクトリで terraform init と terraform plan と tfnotify plan をする
   - 差分がない場合は差分はありません的なメッセージ 

※ apply時もほぼ同様のはず

**Comment by yukio-ugajin** [comment]
```
git --no-pager diff origin/main..HEAD --name-only | xargs -I{} dirname {}
```

**Comment by yukio-ugajin** [comment]
dynamodbでロックする実装もやらないと

**Comment by yukio-ugajin** [comment]
apply戦略はfreeeと同じように
- PRブランチのcodepipelineで手動承認をしたら自動でapply & mainにマージされる
が良い気がしてきた

**Comment by yukio-ugajin** [comment]
>pr作成前のmainとマージ後のmainの差分を抽出する方法（スクリプト）がわからない 

masterに直push を禁止して、必ずPRベースで更新されていく前提なら下記でいけたわ

```
git --no-pager diff HEAD..HEAD^ --name-only | xargs -I{} dirname {} | awk '!a[$0]++{print}'
```

**Comment by yukio-ugajin** [comment]
github actionで組むとシェルで頑張ってdiff取らなくてもいけるっぽい
https://zenn.dev/rinchsan/articles/de981e561eb36ebfab70

**Comment by yukio-ugajin** [comment]
一旦シンプルに「masterにマージされたらapplyする」でやる

**Comment by jinugasachio** [comment]
codebuildでcron実行するためには[codebuild trigger](https://docs.aws.amazon.com/ja_jp/codebuild/latest/userguide/trigger-create.html)なるものが必要みたいだが、現在terraformでは扱っていないリソースのようだった。というか実体はEventBridgeだから不要でしょ？みたいなノリ
https://github.com/hashicorp/terraform-provider-aws/issues/12188

**Comment by jinugasachio** [comment]
https://github.com/jinugasachio/advanced-ecs-on-fargate/issues/1#issuecomment-982611950 

>最終的にたどりついたのは、常にapply するというアプローチです。この方法ではmasterブランチではTerraformの全ディレクトリで変更があろうがなかろうがapplyします。

この手があったか！！！！

**Comment by jinugasachio** [comment]
残to doとして
- [ ] tfsecの導入
- [ ] tflintの導入

があるがそれなりにボリューミーなのでチケット分けてやる
