### ISSUE TITLE
docker compose cliを使ったECSへのデプロイ

### ISSUE THREAD

**Issue by jinugasachio** [jinugasachio/advanced-ecs-on-fargate#16]
もしかしたらこの方が運用簡単そう？要検討
compose.yamlがそのままタスク定義になるっぽい？

- https://matsuand.github.io/docs.docker.jp.onthefly/cloud/ecs-integration/
- https://docs.aws.amazon.com/ja_jp/AmazonECS/latest/developerguide/cmd-ecs-cli-compose.html
- https://docs.aws.amazon.com/ja_jp/AmazonECS/latest/developerguide/cmd-ecs-cli-compose-parameters.html

**Comment by yukio-ugajin** [comment]
一旦不採用で良さそう
論点はタスク定義をappのリポジトリとインフラのリポジトリどちらで管理するかみたいな点だと思う。
fluentbitとか一見appの関心毎ではないものはインフラ側で管理した方が良さそうな気がするのでクローズ
