### ISSUE TITLE
ECSにおけるコンテナへの環境変数注入方法

### ISSUE THREAD

**Issue by jinugasachio** [jinugasachio/advanced-ecs-on-fargate#2]
- ~~タスク定義にベタ書き~~ 却下
- SSMパラメーターストア or Secret Managerで管理（手法は両方同じ, Secret Managerの方が用途には合っている）
  -  タスク定義も編集しないといけない（terraformの編集）ので運用がめんどそう
- envファイルをs3で管理しタスク定義から読み込む
  - 良さそう
  - ただ追加する時はどうしよう？下記でいける？
    - https://qiita.com/suzuki-navi/items/9fdf34163b9915bcaeb7 
 
### 参考
- https://docs.aws.amazon.com/ja_jp/AmazonECS/latest/developerguide/taskdef-envfiles.html
- https://twitter.com/toricls/status/1324532430716297217
- https://medium.com/finatext/ecs-fargate-environmets-on-s3-3553c7397e97

**Comment by yukio-ugajin** [comment]
んーやっぱs3からのenvfile形式が良い気がしてきた
https://github.com/jinugasachio/advanced-ecs-on-fargate/issues/2#issuecomment-949481761 はあるけど、
- 100回に1回くらいの確率
- そもそもserviceがタスク起動をし直してくれるはず
なのでそんなに問題ではなさそう

**Comment by yukio-ugajin** [comment]
疎結合にできるし、やっぱenvfile方針で行くか

**Comment by yukio-ugajin** [comment]
envfileの場合はSSE-S3で暗号化するで良いのか？kmsでできた方が安心なのでは？

**Comment by jinugasachio** [comment]
ちなみにherokuは内部で環境変数を暗号化とかしてたんだろうか
