### ISSUE TITLE
renovateによる更新後の作業をgithub actionsで自動化

### ISSUE THREAD

**Issue by jinugasachio** [jinugasachio/advanced-ecs-on-fargate#38]
### 参考
- [GitHub Actionsとtfupdateを使ってTerraformおよびTerraform Providerのバージョンアップを自動化する](https://techblog.zozo.com/entry/tfupdate-gha#tfupdate%E3%81%AE%E7%B4%B9%E4%BB%8B%E3%81%A8%E4%BD%BF%E3%81%84%E6%96%B9)
- [Terraform開発時のDeveloper Experienceを爆上げする](https://zenn.dev/honmarkhunt/articles/2f03cba1ffe966#6.-tfupdate)
- [tfupdateでTerraform本体/プロバイダ/モジュールのバージョンアップを自動化する](https://qiita.com/minamijoyo/items/1350fb28ae82a3dbb354)

**Comment by yukio-ugajin** [comment]
tfupdateとterraform dependabot の違いがいまいち分かってない
少し古いけど下記あたりかな？

>これを書いてる2019/12/2現在、DependabotはTerraformモジュールしか対応してなくて、Terraform本体やプロバイダには対応していません。むしろ欲しいの本体とプロバイダじゃん？って思った人は私だけではないはず。。。さらにTerraform 0.12(HCL2)対応もされてなくて、まだちょっと実用レベルではなさそうです。

from https://qiita.com/minamijoyo/items/1350fb28ae82a3dbb354

後でちゃんと確認する

**Comment by jinugasachio** [comment]
https://github.com/jinugasachio/advanced-ecs-on-fargate/issues/38#issuecomment-985198184

>これで Dependabot での terraform 対応が完了しました。
・terraform version は自動更新できない
・provider version を自動更新できる。その際、.terraform.lock.hcl も更新されるはず
・以前の Dependabot で対応されていた module version はどうなんだろう？使ってないので分からない

providerは最新verでは対応されたっぽいけどやはり本体のversion更新はされないっぽいかな

**Comment by jinugasachio** [comment]
とりあえず先にdependabot入れるか
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

**Comment by jinugasachio** [comment]
と思ったけどrenovateの方が良いかもしれない
[2021-09-22
Renovate と GitHub Actions で Terraform のバージョンアップを自動化する](https://engineer.retty.me/entry/2021/09/22/123000)

**Comment by jinugasachio** [comment]
>renovateとtfupdateの違いはなんだろう？

できることの大差はなさそう
- [GitHub Actionsとtfupdateを使ってTerraformおよびTerraform Providerのバージョンアップを自動化する](https://techblog.zozo.com/entry/tfupdate-gha#tfupdate%E3%81%AE%E7%B4%B9%E4%BB%8B%E3%81%A8%E4%BD%BF%E3%81%84%E6%96%B9)

**Comment by jinugasachio** [comment]
更新したいもの
- terraform本体
- `.terraform-version`
- provider（AWSなど）
- `lock.hcl` ファイル
- module

**Comment by jinugasachio** [comment]
できることは変わらないけど
差分もdependabotみたいに見れるからrenovateの方が良さそうだな
tfupdateのPRからでは差分を見に行くリンクは生成されない（＝自前で用意する必要がある）

**Comment by jinugasachio** [comment]
### Terraform 自体のバージョンアップについて
- renovateによって[こんな感じ](https://github.com/jinugasachio/advanced-ecs-on-fargate/pull/53)でしている箇所が更新される
- 開発者の手元のバージョンはtfenvを使う限り`.terraform-version` のものに固定（上書き）される
  - そもそもplanもapplyも手元でやることがないならあんま意味ないのかも
- 上書きされるので開発者の手元どのバージョンをtfenv use していようが 各lock.hclファイルはinitをしても差分が出ない 
- よってrenovateのPRに合わせてGA上でinitとplanを実行するのはなくても良いのかも
- それでもplanするのは念の為の確認という意味合いが強い
- もし何かしらの差分がinitで生まれたならplanは失敗するので

**Comment by jinugasachio** [comment]
### 残TODO
