### ISSUE TITLE
バックエンドの設定にTerragrunt

### ISSUE THREAD

**Issue by yukio-ugajin** [jinugasachio/advanced-ecs-on-fargate#93]
バックエンドだけでなくdefault tagとかもDRYに設定できるかも
https://terragrunt.gruntwork.io/docs/getting-started/quick-start/#keep-your-provider-configuration-dry

**Comment by yukio-ugajin** [comment]
というかterragrunt使えばルートでコマンド叩くだけで良い感じになりそう、最高かよ
```
terragrunt run-all plan
```
https://qiita.com/anoneiro/items/db2f2b5fd7d71a9b0fa9

**Comment by yukio-ugajin** [comment]
tfcmtと併用できれば良いのだが

**Comment by yukio-ugajin** [comment]
```
terragrunt run-all plan
```
でinitも合わせてやってくれてそうな雰囲気

**Comment by yukio-ugajin** [comment]
terragruntを使ったCI/CD
https://terragrunt.gruntwork.io/docs/features/keep-your-terragrunt-architecture-dry/#considerations-for-cicd-pipelines

**Comment by jinugasachio** [comment]
https://github.com/jinugasachio/advanced-ecs-on-fargate/issues/93#issuecomment-1003395862 

やってくれる
https://terragrunt.gruntwork.io/docs/features/auto-init/
